kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "parksmap-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/nenadmudri/adv_openshift_homework.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ParksMap/Jenkinsfile
